### ISSUE TITLE
Why use `return` statement

### ISSUE THREAD

**Issue by keisukeYamagishi** [kishikawakatsumi/swift-power-assert#184]
I think you should not use `return` statement because this is so simple and not redundant, if use `return` statement this is not simple and redundant

https://github.com/kishikawakatsumi/swift-power-assert/blob/0899fee1d6db137350b14f2f8aa49b04a172e872/Sources/PowerAssertPlugin/PowerAssertRewriter.swift#L166

```Swift
override func visit(_ node: ArrowExprSyntax) -> ExprSyntax {
    return super.visit(node)
}
```

Like this ☟

```Swift
override func visit(_ node: ArrowExprSyntax) -> ExprSyntax {
    super.visit(node)
}
```

**Comment by kishikawakatsumi** [comment]
Closes as resolved
