### ISSUE TITLE
Testing next steps

### ISSUE THREAD

**Issue by wti** [kishikawakatsumi/swift-power-assert#299]
Thank you for an amazing contribution!  This really promises to reduce unnecessary code in testing.

I'd like to contribute some tests to fill out validation; do you have plans/directions for that?

I can just add some of the missing tests (e.g. expressions), matching your current approach.

But my concern with the approach comparing String output is that tests may become brittle and prone to fail with SwiftSyntax upgrades (likely in the near term), with the result that a large test suite taxes every upgrade with a multitude of small changes to the expected results. We may need different expected results for each format-breaking version of SwiftSyntax, which may be hard to manage in code.

SwiftSyntax itself tests using syntax-tree comparison, but that approach can be arduous.

Stepping back a bit to consider what needs testing, I wonder how we think asserts could fail (i.e., what's the fault model)?  Coverage analytically would be simple expressions building through relevant combinations.  For some faults, we might instead prove they're impossible based on how the asserts are constructed, reducing the combinations required.

Regardless, we could just improve the ergonomics of the string-based approach.  For individual tests, I started down the road of showing exact differences on failure, to pinpoint the text/syntax difference to make it easier to correct results.

I wonder if some kind of capture/replay for tests or suites would be in order, for suite-wide version upgrades and test development.  If we streamed actual results to some resource file and validated the result, a harness could read the expected output for each test.  Then on SwiftSyntax upgrade we could simply stream the actual output for all tests, and verify by inspection that any changes are correct.  We could handle different SwiftSyntax versions at runtime using different expected-result files, instead of needing different versions of the test suite.  I believe the capture/replay resource can be markdown, making the tests self-documenting and tree-form, which helps since the test developer will have to sync the expression in the code with the expected-result file.  Longer term, the capture-replay approach might be helpful for other macro developers, it and it might be interesting to generate test cases as well.

Time (really attention) is always a factor. Tree comparisons and fault models require some investigation, and the imminent release of 5.9 may result in lots of client traffic soon.

Perhaps the steps should be:

1.  Fill in some expression tests, using current approach.
2. Update the harness to point at specific changes on failure for each test, and prototype in new tests.
3. Fill in the other coverage gaps you'd like to address 
4. Experiment to validate capture/replay as a parallel mode for tests

That would set up decisions about whether to pursue capture/replay or other investigations and approaches, with the preliminary question of whether to convert existing tests to capture/replay, perhaps before another SwiftSyntax upgrade.

Thoughts?

**Comment by kishikawakatsumi** [comment]
Current E2E testing is required for this library. This is because the source code output by macros is not always compileable (e.g., type inference timeouts).

It is expected that SwiftSyntax updates will break it. Rather, it is important to be able to detect that SwiftSyntax updates break things.

We do not have a vision for other tests at this time. Good methods are welcome.

**Comment by wti** [comment]
Thanks for your reply - Agreed.  I think my goal was to improve coverage (for more notice with SwiftSyntax breaks things) but also to make it easier to write and debug tests, and to track API/behavior changes in SwiftSyntax.  If I can find time I'll proceed with the steps.

**Comment by kishikawakatsumi** [comment]
That is correct. Coverage is an important guideline for measuring soundness. And you are also right that the current E2E test is impossible to debug. That is something we would like to improve.

**Comment by wti** [comment]
Closing b/c plan made.  Sorry I've become backlogged atm, but I will still try to follow up.
